name: Update Events Calendar

on:
  schedule:
    - cron: "0 9 * * *"  # Run every day at 9:00 UTC (3AM Laramie time)
  workflow_dispatch:    # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          playwright install chromium

      - name: Run scraper
        run: |
          python build_ics.py

      - name: Commit changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add docs/events.ics
          git commit -m "Update events.ics" || echo "No changes to commit"
          git push
